language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

before_script:
  - composer install
  - php app/console example:configure:environment --variable="EXAMPLE_DEBUG=true"
  - php app/console example:database:create
  - php app/console example:schema:create
  - php app/console example:fixtures:load

script: vendor/bin/behat
