<?php

// See: http://silex.sensiolabs.org/doc/usage.html#bootstrap
$app['debug'] = isset($_ENV['EXAMPLE_DEBUG']) ? $_ENV['EXAMPLE_DEBUG'] : false;

// Whitelist of environment variables to register.
// Docker related. Assumes that a MySQL container was started and named "mysql".
// See: https://docs.docker.com/userguide/dockerlinks/
$app['environment.variables.whitelist'] = array(
    'MYSQL_ENV_MYSQL_ROOT_PASSWORD' => 'EXAMPLE_MYSQL_PASSWORD',
    'MYSQL_PORT_3306_TCP_ADDR' => 'EXAMPLE_MYSQL_HOST',
    'MYSQL_PORT_3306_TCP_PORT' => 'EXAMPLE_MYSQL_PORT',
);

// File path to the file generated by the "example:configure:environment" command.
// If the file exists, it register the variables listed on the variables whitelist to the server environment.
$app['environment.variables.file'] = __DIR__.'/../../.env';

$app['doctrine.dbal.options'] = array(
    'db.options' => array(
        'driver'   => 'pdo_mysql',
        'dbname'   => getenv('EXAMPLE_MYSQL_DATABASE') ?: 'example',
        'host'     => getenv('EXAMPLE_MYSQL_HOST') ?: '127.0.0.1',
        'user'     => getenv('EXAMPLE_MYSQL_USER') ?: 'root',
        'password' => getenv('EXAMPLE_MYSQL_PASSWORD') ?: '',
        'port'     => getenv('EXAMPLE_MYSQL_PORT') ?: 3306,
    ),
);

$app['twig.options'] = array(
    'twig.path' => array(
        __DIR__.'/../views',
        __DIR__.'/../../src/Example/Resources/views',
    ),
);
